### ISSUE TITLE
Property 'selectTab' does not exist on type 'BottomNavigation'.

### ISSUE THREAD

**Issue by keerl** [henrychavez/nativescript-bottom-navigation#59]
Since updating to 1.5.0 I am getting an error that selectTab() does not exist anymore, breaking my app. I noticed a restructuring of the code in 1.5.0 and the location of selectTab() moved probably causing the issue.

`Property 'selectTab' does not exist on type 'BottomNavigation'.`

**Comment by henrychavez** [comment]
Can u show me a piece of your code when you are trying to use the select Tab function?

**Comment by keerl** [comment]
Here is the gist of it.
```
private _bottomNavigation: BottomNavigation;

bottomNavigationLoaded(args) {
    this._bottomNavigation = args.object;
}

changeTab(tab: number) {
    this._bottomNavigation.selectTab(tab);
}
```

**Comment by henrychavez** [comment]
When are you calling the changeTab function?

**Comment by keerl** [comment]
It gets called off an observable from a service, but I don't think the issue is where it is being called from. Typescript does not think the function exists and won't compile at all.

**Comment by henrychavez** [comment]
Uhmm the error occurs when you are trying to compile? Or when the app is running? I don't understand, I need the complete info to have an idea of why the error happen or if what you're trying to do is correct

**Comment by armpogart** [comment]
I think the problem is that published library typescript declarations file lack some signatures. Here is `index.d.ts` from latest version of your library:
```typescript
import { EventData } from 'tns-core-modules/data/observable';
import { AddChildFromBuilder, View } from 'tns-core-modules/ui/core/view';
import { BottomNavigationBase, BottomNavigationTabBase } from './bottom-navigation.common';

export declare interface OnTabPressedEventData extends EventData {
  index: number;
}

export declare interface OnTabReselectedEventData extends EventData {
  index: number;
}

export declare interface OnTabSelectedEventData extends EventData {
  oldIndex: number;
  newIndex: number;
}

export type TitleVisibility = 'always' | 'selected' | 'never';

export declare class BottomNavigation extends BottomNavigationBase {

  protected titleVisibilityOptions;

  readonly android: any;
  readonly ios: any;

  private _delegate;

  constructor();

  public createTabs(tabs: BottomNavigationTab[]): void;

  protected selectTabNative(index: number): void;
}

export declare class BottomNavigationTab extends BottomNavigationTabBase {
  constructor(title: string, icon: string, selectable?: boolean, parent?: WeakRef<BottomNavigationBase>);
}
```

**Comment by henrychavez** [comment]
hi all,
thanks for letting me know, I'm kinda busy these days but I'll try to fix it this weekend.

Pull request are welcome too :D

**Comment by henrychavez** [comment]
I just release the version 1.5.1 with the fix.

Happy coding!
